sudo: required

language: node_js
node_js:
    - "lts/*"

language: python
python:
    - "3.6.7"

services:
    - docker

jobs:
    include:
        - stage: test
	  before_install:
              - sudo pip install --upgrade pip
          install:
              - docker build -t synbiohub/synbiohub:snapshot-standalone -f docker/Dockerfile .
              - sudo pip install -r tests/test_requirements.txt
          script: tests/test.sh

        - stage: push
          install:
              - docker build -t synbiohub/synbiohub:snapshot-standalone -f docker/Dockerfile .
          script: docker/push.sh
          if: branch = master AND type = push

