sudo: required

services:
    - docker

script:
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      docker build -t synbiohub/synbiohub:snapshot-standalone -f docker/Dockerfile-standalone docker;
      docker push synbiohub/synbiohub:snapshot-standalone;
      fi
