name: Run release 

on: 
  release:
    types: [published]

jobs:

  retag-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
          RELEASE=$(echo $GITHUB_REF | cut -d'/' -f 3)
          docker build . --file docker/Dockerfile --tag synbiohub/synbiohub:$RELEASE-standalone
    - name: Push the image to Docker Hub
      run: |
          RELEASE=$(echo $GITHUB_REF | cut -d'/' -f 3)
          docker push synbiohub/synbiohub:$RELEASE-standalone
  update-compose:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            repository: synbiohub/synbiohub-docker
            ref: snapshot
        - name: Change tag
          run: |
            RELEASE=$(echo $GITHUB_REF | cut -d'/' -f 3)
            sed -i "s/snapshot/$RELEASE/g" docker-compose.yml docker-compose.version.yml
        - name: Commit to master and push
          run: | 
              RELEASE=$(echo $GITHUB_REF | cut -d'/' -f 3)
              git checkout master
              git commit -am "Update to version $RELEASE"
              gitA
        - name: Push changes
          uses: ad-m/github-push-action@master
          with: 
            github_token: ${{ secrets.ZACH_GITHUB_TOKEN }}
    
