name: Run release 

on: 
  release:
    types: [published]

jobs:

  retag-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
          RELEASE=$(echo $GITHUB_REF | cut -d'/' -f 3)
          docker build . --file docker/Dockerfile --tag synbiohub/synbiohub:$RELEASE-standalone
    - name: Push the image to Docker Hub
      env:
          DH_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DH_PASSWORD: ${{ secrets.DOCKER_OASSWORD }}
      run: |
          RELEASE=$(echo $GITHUB_REF | cut -d'/' -f 3)
          echo $DH_PASSWORD | docker login -u "$DH_USERNAME" --password-stdin
          docker push synbiohub/synbiohub:$RELEASE-standalone
  update-compose:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            repository: synbiohub/synbiohub-docker
        - name: Change tag
          run: |
            RELEASE=$(echo $GITHUB_REF | cut -d'/' -f 3)
            sed -i "s/synbiohub\/synbiohub:.*-standalone/synbiohub\/synbiohub:$RELEASE-standalone/g" docker-compose.yml docker-compose.version.yml
            git commit -am "Update to version $RELEASE"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with: 
            github_token: ${{ secrets.ZACH_GITHUB_TOKEN }}
    
