name: Test and publish snapshot

on: push

jobs:
  build: 
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file docker/Dockerfile --tag synbiohub/synbiohub:snapshot-standalone
    - name: Package image
      run: |
        docker save synbiohub/synbiohub:snapshot-standalone | gzip > sbh.tar.gz
    - uses: actions/upload-artifact@v2
      with:
        name: sbh-image
        path: sbh.tar.gz
  sboltests:
    name: SBOL Test Suite
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: sbh-image
    - name: Import saved Docker image
      run: |
        cat sbh.tar.gz | docker import - synbiohub/synbiohub:snapshot-standalone
    - name: Install test dependencies
      run: |
        pip install -r tests/test_requirements.txt
    - name: Run tests
      run: |
        tests/sbolsuite.sh
  sbhtests:
    name: SynBioHub Test Suite
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: sbh-image
    - name: Import saved Docker image
      run: |
        cat sbh.tar.gz | docker import - synbiohub/synbiohub:snapshot-standalone
    - name: Install test dependencies
      run: |
        pip install -r tests/test_requirements.txt
    - name: Run tests
      run: |
        tests/test.sh --stopaftertestsuite
  publish:
    name: Publish snapshot image
    needs: [sboltests, sbhtests]
    runs-on: ubuntu-latest
    if: endsWith(github.ref, 'master')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: sbh-image
    - name: Import saved Docker image
      run: |
        cat sbh.tar.gz | docker import - synbiohub/synbiohub:snapshot-standalone
    - uses: azure/docker-login@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the image to Docker Hub
      run: |
        docker push synbiohub/synbiohub:snapshot-standalone
    - name: Trigger SD2 redeploy
      env: 
        SD2_USER: ${{ secrets.SD2_USER }}
        SD2_TOKEN: ${{ secrets.SD2_TOKEN }}
      run: | 
        curl -X POST --user $SD2_USER:$SD2_TOKEN http://jenkins.sd2e.org/job/Synbiohub/job/Redeploy%20to%20dev%20server/build | 
